#!/bin/bash

#################
# CONFIGURATION #
#################

# set defaults for variables
vaultFilePattern="ANSIBLE_VAULT;1.1"
vaultPasswordFile="/tmp/vault-password-file-$(date +%s%N).txt"
vaultFilesCacheFile=".vault-files"

#############
# FUNCTIONS #
#############

# --------------------------------------------------------
# Function for creating log entries on the console
# --------------------------------------------------------
# $1 - Log level
# $2 - Log text
# --------------------------------------------------------
function log() {

    # read parameters
    local level="$1"
    local text="$2"

    # create log message
    local now=$(date +"%d-%m-%Y %H:%M:%S")
    echo -e "\n$now [$level] $text\n"
}

# --------------------------------------------------------
# Function to display a confirm message on the console
# --------------------------------------------------------
# $1 - Confirm message
# --------------------------------------------------------
function confirm() {

    # read parameters
    local question="$1"

    echo ""
    read -r -p "$question [Y/n] " answer
    echo ""

    case "$answer" in
        [yY][eE][sS]|[yY])
            return 0
        ;;
        *)
            return 1
        ;;
    esac
}

# ---------------------------------------------------------------
# Function for reading the vault password and save it to a file
# ---------------------------------------------------------------
# $1 - Does the vault password need to be confirmed
# ---------------------------------------------------------------
function createVaultPasswordFile() {

    # read parameters
    local confirm="$1"
    
    # logging
    log "INFO" "Creating vault password file '$vaultPasswordFile'"
    
    # check if vault password needs confirmation
    if [ "$confirm" == "true" ]
    then
        # read the new vault password from command line
        read -s -p "New Vault Password: " vaultPassword
        echo ""
        read -s -p "New Vault Password (Confirm): " vaultPasswordConfirm
        echo ""
        echo ""

        # check if both vault passwords are matching
        if [ "$vaultPassword" != "$vaultPasswordConfirm" ]
        then
            log "ERROR" "You have entered different vault passwords. Please try again."
            exit -1
        fi
    else
        # read the current vault password from command line
        read -s -p "Current Vault Password: " vaultPassword
        echo ""
    fi

    # create vault password file
    echo "$vaultPassword" > "$vaultPasswordFile"

    # limit permissions for vault password file
    chmod 600 "$vaultPasswordFile"
}

# ---------------------------------------------------------------
# Function for removing the vault password file
# ---------------------------------------------------------------
function removeVaultPasswordFile() {
    
    # logging
    log "INFO" "Removing vault password file '$vaultPasswordFile'"

    # remove vault password file
    rm -f "$vaultPasswordFile"
}

# ---------------------------------------------------------------
# Function for creating the vault files cache file
# ---------------------------------------------------------------
function createVaultFilesCacheFile() {
    
    # logging
    log "INFO" "Creating vault files cache file '$vaultFilesCacheFile'"

    # create vault files cache file
    grep -rl "$vaultFilePattern" * > "$vaultFilesCacheFile"
}

# ---------------------------------------------------------------
# Function for removing the vault files cache file
# ---------------------------------------------------------------
function removeVaultFilesCacheFile() {
    
    # logging
    log "INFO" "Removing vault files cache file '$vaultFilesCacheFile'"

    # remove vault files cache file
    rm -f "$vaultFilesCacheFile"
}

# ---------------------------------------------------------------
# Function for decrypting all vault files
# ---------------------------------------------------------------
function decrypt() {

    # check if vault files cache file already exists
    if [ ! -f "$vaultFilesCacheFile" ]
    then

        # create vault password file
        createVaultPasswordFile

        # create vault files cache
        createVaultFilesCacheFile

        # logging
        log "INFO" "Decrypting all vault files"

        # iterate over all vault files and decrypt them
        cat "$vaultFilesCacheFile" | while read vaultFile
        do
            # Logging
            echo "Decrypting vault file '$vaultFile'"

            # decrypt current vault file
            ansible-vault decrypt "$vaultFile" --vault-password-file "$vaultPasswordFile" > /dev/null 2>&1
        done

        # remove vault password file
        removeVaultPasswordFile
    else

        # logging
        log "ERROR" "Vault files cache file '$vaultFilesCacheFile' already exists. Please revert all of your local changes and execute the cleanup command."
        exit -1
    fi
}

# ---------------------------------------------------------------
# Function for encrypting all vault files
# ---------------------------------------------------------------
function encrypt() {

    # check if vault files cache file exists
    if [ -f "$vaultFilesCacheFile" ]
    then

        # create vault password file
        createVaultPasswordFile "true"

        # logging
        log "INFO" "Encrypting all vault files"

        # iterate over all vault files and encrypt them
        cat "$vaultFilesCacheFile" | while read vaultFile
        do
            # Logging
            echo "Encrypting vault file '$vaultFile'"

            # encrypt current vault file
            ansible-vault encrypt "$vaultFile" --vault-password-file "$vaultPasswordFile" > /dev/null 2>&1
        done

        # remove vault files cache
        removeVaultFilesCacheFile

        # remove vault password file
        removeVaultPasswordFile
    else

        # logging
        log "ERROR" "Vault file cache file '$vaultFilesCacheFile' does not exist. Please decrypt all vault files before executing this command."
        exit -1
    fi
}

# ---------------------------------------------------------------
# Function to rekey all vault files
# ---------------------------------------------------------------
function rekey() {

    # logging
    log "INFO" "Rekeying all vault files"

    # decrypt all vault files
    decrypt

    # encrypt all vault files
    encrypt
}

# ---------------------------------------------------------------
# Function to search secrets in all vault files
# ---------------------------------------------------------------
function search() {

    # create vault password file
    createVaultPasswordFile

    # read secret text from command line
    read -s -p "Secret Search Text: " secretText
    echo ""

    # create vault files cache
    createVaultFilesCacheFile

    # logging
    log "INFO" "Searching secret text in all vault files"

    # iterate over all vault files and search for the secret
    cat "$vaultFilesCacheFile" | while read vaultFile
    do
        output="$(ansible-vault view $vaultFile --vault-password-file $vaultPasswordFile | grep -F $secretText)"
        if [ "$output" != "" ]
        then
            echo "Secret text found in file '$vaultFile'"
        fi
    done

    # remove vault files cache
    removeVaultFilesCacheFile

    # remove vault password file
    removeVaultPasswordFile
}

# ---------------------------------------------------------------
# Function to cleanup vault files cache file
# ---------------------------------------------------------------
function cleanup() {

    # confirm removal of vault files cache file
    if confirm "Do you really want to cleanup the vault files cache file '$vaultFilesCacheFile'? You will loose all file paths from previous vault files!"
    then
        removeVaultFilesCacheFile
    fi
}

# ---------------------------------------------------------------
# Function for printing the usage of this script
# ---------------------------------------------------------------
function usage() {

    # print help text
    cat <<USAGE
Usage:
  $scriptName [Options] <Args>

Options:
  -c    Cleanup vault files cache file
  -d    Decrypt all vault files
  -e    Encrypt all vault files
  -h    Show this help text
  -r    Rekey (change password for) all vault files
  -s    Search for secret text in all vault files

Example:
  $scriptName -s

USAGE

    # exit with error
    exit -1
}


##########
# SCRIPT #
##########

# echo script banner
echo ""
echo "#########################"
echo "# Ansible Vault Wrapper #"
echo "#########################"
echo ""

# get script folder
scriptPath="$(readlink -f $0)"
scriptFolder="$(dirname $scriptPath)"
scriptName="$(basename $scriptPath)"

# show help text if action is not set
if [ "$1" == "" ]
then
    usage
    exit -1
fi

# get command line args
while getopts cdehrs opt
do
    case $opt in
        c)
            cleanup
        ;;
        d)
            decrypt
        ;;
        e)
            encrypt
        ;;
        h)
            usage
            exit -1
        ;;
        r)
            rekey
        ;;
        s)
            search
        ;;   
        \?)
            log "ERROR" "Please specify a valid option"
            exit -1
        ;;
    esac
done   